### ISSUE TITLE
Heat Rejection Design Study

### ISSUE THREAD

**Issue by A-Ghoul** [Colorado-School-of-Mines-Robotics-Club/MATE_ROV_CAD_AQUA-SQUATCH#3]
- Cross-reference all electronics that are going in the tube
	- May need different estimates for electronics as we update our plan for hardware
		- Need to keep close contact with the electronics team.
	- What is the heat envelope?
		- What is the maximum amount of heat that we would generate in a given second?
		- What is a more reasonable average amount of heat we would generate?
		- For both, what is the total heat output (in Joules) that we produce over the course of ~20 min

- If we assume a well-mixed atmosphere in the tube, how much heat can we reject from the enclosure itself?
	- Run a study on both an 8" and 6" ID tube
		- Assume both tubes have a wall thickness of 1/4"
	- Assume the front cap is 1/2" thick, flat acrylic
	- Assume the rear cap is made of 1/4" thick 304 Stainless steel (don't model pass thru-holes)
		- also test with 1/4" thick aluminum (any, preferably 5052 alloy, but any alloy is fine)
	- Assume Tube is 24" long
		- If time check 12" long tube/how every inch of tube length affects heat rejection (likely not much)
	- Assume the maximum permissible internal temperature is 80 deg C
		- Also check heat output at 75 deg C, 70 deg C, 65 deg C, ..., 20 deg C if time permits
		- Required to at least check 20 deg C in addition to 80 deg C
	- Assume external fluid is ambient temperature (20 deg C) water.
		- If time/capability, plot how heat rejection changes with changing depth (pressure), temperature, and the velocity of the external fluid (assume flow direction is from the front, acrylic cap to the rear, metal cap)

- Find how much more heat we produce than we reject passively at our maximum permissible temperature (80 deg C)
	- If we reject more heat than we produce at 80 deg C, what is the temperature at which it is equal (approximately)?
	- Is the difference small enough that we can assume that the tube won't get too warm during the course of a competition
	  run (~20 min)?
	- If the difference is significant enough:
		- Does gluing fins to the metal plate help significantly?
		- Does making the front plate metal as well help significantly?

**Comment by RedshiftVelocities** [comment]
![rov-heat-study-1](https://user-images.githubusercontent.com/43499473/179328586-02ed32c3-24e8-41c2-933a-c1b02e07eaa0.png)
![rov-heat-study-2](https://user-images.githubusercontent.com/43499473/179328588-884a6020-5c4c-48a6-a92e-bf08aeec85fc.png)
Some preliminary calculations. If you have the patience and can read my abysmal handwriting, I'd appreciate someone checking my work. I assumed a 6" enclosure, 350k (~75c) internal temp, 300k (~25c) external.  Estimating the internal heat load at 300w (calculations in Discord, I can provide them if necessary), even the tube alone will _theoretically_ be enough. But I highly doubt that will hold up at all in practice; the thermal transfer between the heat-producing devices and the air in the enclosure, as well as the air and the internal walls, will be the limiting factors. However, a steel endcap will provide vastly better heat transfer than the rest of the enclosure put together. and an aluminum endcap will provide an order of magnitude more transfer over that. 

Based on this, my thoughts are that we should either focus more on the components->air junction, or having a direct metal path from the components to a metal endcap. I'll have to do some more calculations in that regard, probably tomorrow.
